version: 2
jobs:
  build:
    environment:
    docker:
      - image: mhart/alpine-node:6.11
    working_directory: /home/ubuntu/${CIRCLE_PROJECT_REPONAME}
    steps:
      - setup_docker_engine
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            apk add --update curl
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BUILD_NUM} .
      - run:
          name: npm install
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Push Docker Image
          command: |
            set -x
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BUILD_NUM}
            docker push ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest