version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: install docker
          command: ./scripts/install_docker.sh
      - run:
          name: Build and push Docker image
          command: |
            IMAGE="${CIRCLE_PROJECT_USERNAME}/docker-devops-test-webapp:${CIRCLE_BUILD_NUM}"
            docker build -t $IMAGE .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push $IMAGE